// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matrix_multiply_alt2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        B_address0,
        B_ce0,
        B_q0,
        C_address0,
        C_ce0,
        C_we0,
        C_d0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state19 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] A_address0;
output   A_ce0;
input  [31:0] A_q0;
output  [3:0] B_address0;
output   B_ce0;
input  [31:0] B_q0;
output  [3:0] C_address0;
output   C_ce0;
output   C_we0;
output  [31:0] C_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg A_ce0;
reg B_ce0;
reg C_ce0;
reg C_we0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [4:0] indvar_flatten1_reg_116;
reg   [1:0] Col_assign_2_reg_127;
reg   [3:0] indvar_flatten_reg_138;
reg   [1:0] Row_assign_reg_149;
reg   [1:0] Col_assign_reg_160;
wire   [0:0] exitcond_flatten1_fu_181_p2;
reg   [0:0] exitcond_flatten1_reg_403;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
wire    ap_block_state7_pp0_stage0_iter5;
wire    ap_block_state8_pp0_stage0_iter6;
wire    ap_block_state9_pp0_stage0_iter7;
wire    ap_block_state10_pp0_stage0_iter8;
wire    ap_block_state11_pp0_stage0_iter9;
wire    ap_block_state12_pp0_stage0_iter10;
wire    ap_block_state13_pp0_stage0_iter11;
wire    ap_block_state14_pp0_stage0_iter12;
wire    ap_block_state15_pp0_stage0_iter13;
wire    ap_block_state16_pp0_stage0_iter14;
wire    ap_block_state17_pp0_stage0_iter15;
wire    ap_block_state18_pp0_stage0_iter16;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond_flatten1_reg_403_pp0_iter1_reg;
reg   [0:0] exitcond_flatten1_reg_403_pp0_iter2_reg;
reg   [0:0] exitcond_flatten1_reg_403_pp0_iter3_reg;
reg   [0:0] exitcond_flatten1_reg_403_pp0_iter4_reg;
reg   [0:0] exitcond_flatten1_reg_403_pp0_iter5_reg;
reg   [0:0] exitcond_flatten1_reg_403_pp0_iter6_reg;
wire   [4:0] indvar_flatten_next1_fu_187_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] tmp_mid2_fu_225_p3;
reg   [0:0] tmp_mid2_reg_412;
reg   [0:0] tmp_mid2_reg_412_pp0_iter1_reg;
reg   [0:0] tmp_mid2_reg_412_pp0_iter2_reg;
reg   [0:0] tmp_mid2_reg_412_pp0_iter3_reg;
reg   [0:0] tmp_mid2_reg_412_pp0_iter4_reg;
reg   [0:0] tmp_mid2_reg_412_pp0_iter5_reg;
reg   [0:0] tmp_mid2_reg_412_pp0_iter6_reg;
reg   [0:0] tmp_mid2_reg_412_pp0_iter7_reg;
reg   [0:0] tmp_mid2_reg_412_pp0_iter8_reg;
reg   [0:0] tmp_mid2_reg_412_pp0_iter9_reg;
reg   [0:0] tmp_mid2_reg_412_pp0_iter10_reg;
reg   [0:0] tmp_mid2_reg_412_pp0_iter11_reg;
reg   [0:0] tmp_mid2_reg_412_pp0_iter12_reg;
reg   [0:0] tmp_mid2_reg_412_pp0_iter13_reg;
reg   [0:0] tmp_mid2_reg_412_pp0_iter14_reg;
reg   [0:0] tmp_mid2_reg_412_pp0_iter15_reg;
wire   [0:0] tmp_mid2_13_fu_245_p3;
reg   [0:0] tmp_mid2_13_reg_416;
reg   [0:0] tmp_mid2_13_reg_416_pp0_iter1_reg;
reg   [0:0] tmp_mid2_13_reg_416_pp0_iter2_reg;
reg   [0:0] tmp_mid2_13_reg_416_pp0_iter3_reg;
reg   [0:0] tmp_mid2_13_reg_416_pp0_iter4_reg;
reg   [0:0] tmp_mid2_13_reg_416_pp0_iter5_reg;
reg   [0:0] tmp_mid2_13_reg_416_pp0_iter6_reg;
reg   [0:0] tmp_mid2_13_reg_416_pp0_iter7_reg;
reg   [0:0] tmp_mid2_13_reg_416_pp0_iter8_reg;
reg   [0:0] tmp_mid2_13_reg_416_pp0_iter9_reg;
reg   [0:0] tmp_mid2_13_reg_416_pp0_iter10_reg;
reg   [0:0] tmp_mid2_13_reg_416_pp0_iter11_reg;
reg   [0:0] tmp_mid2_13_reg_416_pp0_iter12_reg;
reg   [0:0] tmp_mid2_13_reg_416_pp0_iter13_reg;
reg   [0:0] tmp_mid2_13_reg_416_pp0_iter14_reg;
reg   [0:0] tmp_mid2_13_reg_416_pp0_iter15_reg;
wire   [1:0] tmp_i_i_mid2_v_fu_253_p3;
reg   [1:0] tmp_i_i_mid2_v_reg_420;
wire   [1:0] Col_assign_mid2_fu_291_p3;
reg   [1:0] Col_assign_mid2_reg_427;
wire   [1:0] tmp_11_mid2_fu_299_p3;
reg   [1:0] tmp_11_mid2_reg_432;
wire   [1:0] c_fu_307_p2;
wire   [3:0] indvar_flatten_next_fu_319_p3;
wire   [4:0] tmp_22_fu_392_p2;
reg   [4:0] tmp_22_reg_459;
reg   [4:0] tmp_22_reg_459_pp0_iter2_reg;
reg   [4:0] tmp_22_reg_459_pp0_iter3_reg;
reg   [4:0] tmp_22_reg_459_pp0_iter4_reg;
reg   [4:0] tmp_22_reg_459_pp0_iter5_reg;
reg   [4:0] tmp_22_reg_459_pp0_iter6_reg;
reg   [31:0] cast_in_a_reg_464;
reg   [31:0] cast_in_b_reg_469;
wire   [31:0] grp_fu_177_p2;
reg   [31:0] mult_reg_474;
reg   [31:0] mult_reg_474_pp0_iter7_reg;
reg   [3:0] C_addr_reg_480;
reg   [3:0] C_addr_reg_480_pp0_iter8_reg;
reg   [3:0] C_addr_reg_480_pp0_iter9_reg;
reg   [3:0] C_addr_reg_480_pp0_iter10_reg;
reg   [3:0] C_addr_reg_480_pp0_iter11_reg;
reg   [3:0] C_addr_reg_480_pp0_iter12_reg;
reg   [3:0] C_addr_reg_480_pp0_iter13_reg;
reg   [3:0] C_addr_reg_480_pp0_iter14_reg;
reg   [3:0] C_addr_reg_480_pp0_iter15_reg;
reg   [3:0] sum_mult_addr_reg_485;
reg   [3:0] sum_mult_addr_reg_485_pp0_iter8_reg;
reg   [3:0] sum_mult_addr_reg_485_pp0_iter9_reg;
reg   [3:0] sum_mult_addr_reg_485_pp0_iter10_reg;
reg   [3:0] sum_mult_addr_reg_485_pp0_iter11_reg;
reg   [3:0] sum_mult_addr_reg_485_pp0_iter12_reg;
reg   [3:0] sum_mult_addr_reg_485_pp0_iter13_reg;
reg   [3:0] sum_mult_addr_reg_485_pp0_iter14_reg;
wire   [31:0] sum_mult_q0;
reg    ap_enable_reg_pp0_iter8;
wire   [31:0] grp_fu_171_p2;
reg   [31:0] tmp_13_reg_496;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
wire   [3:0] sum_mult_address0;
reg    sum_mult_ce0;
reg    sum_mult_we0;
reg    sum_mult_ce1;
reg    sum_mult_we1;
reg   [1:0] ap_phi_mux_Col_assign_2_phi_fu_131_p4;
wire    ap_block_pp0_stage0;
reg   [1:0] ap_phi_mux_Row_assign_phi_fu_153_p4;
wire   [63:0] tmp_28_cast_fu_373_p1;
wire  signed [63:0] tmp_29_cast_fu_387_p1;
wire   [63:0] tmp_30_cast_fu_398_p1;
wire   [0:0] exitcond_flatten_fu_199_p2;
wire   [1:0] k_fu_193_p2;
wire   [0:0] tmp_mid1_fu_213_p2;
wire   [0:0] tmp3_fu_219_p2;
wire   [0:0] tmp_mid1_12_fu_233_p2;
wire   [0:0] tmp_2_fu_239_p2;
wire   [0:0] exitcond_fu_267_p2;
wire   [0:0] not_exitcond_flatten_fu_261_p2;
wire   [1:0] Row_assign_mid_fu_205_p3;
wire   [0:0] exitcond_mid_fu_273_p2;
wire   [0:0] tmp_18_fu_285_p2;
wire   [1:0] r_fu_279_p2;
wire   [3:0] indvar_flatten_op_fu_313_p2;
wire   [3:0] tmp_s_fu_330_p3;
wire   [4:0] p_shl1_cast_fu_337_p1;
wire   [4:0] tmp_i_i_mid2_cast_fu_327_p1;
wire   [3:0] tmp_fu_350_p3;
wire   [4:0] p_shl_cast_fu_357_p1;
wire   [4:0] tmp_11_mid2_cast_fu_347_p1;
wire   [4:0] tmp_19_fu_361_p2;
wire   [4:0] tmp_20_fu_367_p2;
wire   [4:0] tmp_i_i4_cast_fu_378_p1;
wire   [4:0] tmp_17_fu_341_p2;
wire   [4:0] tmp_21_fu_381_p2;
wire    ap_CS_fsm_state19;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
end

matrix_multiply_abkb #(
    .DataWidth( 32 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
sum_mult_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sum_mult_address0),
    .ce0(sum_mult_ce0),
    .we0(sum_mult_we0),
    .d0(mult_reg_474),
    .q0(sum_mult_q0),
    .address1(sum_mult_addr_reg_485_pp0_iter14_reg),
    .ce1(sum_mult_ce1),
    .we1(sum_mult_we1),
    .d1(grp_fu_171_p2)
);

matrix_multiply_tcud #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
matrix_multiply_tcud_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_mult_q0),
    .din1(mult_reg_474_pp0_iter7_reg),
    .ce(1'b1),
    .dout(grp_fu_171_p2)
);

matrix_multiply_tdEe #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
matrix_multiply_tdEe_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(cast_in_a_reg_464),
    .din1(cast_in_b_reg_469),
    .ce(1'b1),
    .dout(grp_fu_177_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter16 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten1_reg_403 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        Col_assign_2_reg_127 <= tmp_i_i_mid2_v_reg_420;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        Col_assign_2_reg_127 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten1_fu_181_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Col_assign_reg_160 <= c_fu_307_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        Col_assign_reg_160 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten1_reg_403 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        Row_assign_reg_149 <= tmp_11_mid2_reg_432;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        Row_assign_reg_149 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten1_fu_181_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten1_reg_116 <= indvar_flatten_next1_fu_187_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten1_reg_116 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten1_fu_181_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_reg_138 <= indvar_flatten_next_fu_319_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_138 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_reg_403_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        C_addr_reg_480 <= tmp_30_cast_fu_398_p1;
        sum_mult_addr_reg_485 <= tmp_30_cast_fu_398_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        C_addr_reg_480_pp0_iter10_reg <= C_addr_reg_480_pp0_iter9_reg;
        C_addr_reg_480_pp0_iter11_reg <= C_addr_reg_480_pp0_iter10_reg;
        C_addr_reg_480_pp0_iter12_reg <= C_addr_reg_480_pp0_iter11_reg;
        C_addr_reg_480_pp0_iter13_reg <= C_addr_reg_480_pp0_iter12_reg;
        C_addr_reg_480_pp0_iter14_reg <= C_addr_reg_480_pp0_iter13_reg;
        C_addr_reg_480_pp0_iter15_reg <= C_addr_reg_480_pp0_iter14_reg;
        C_addr_reg_480_pp0_iter8_reg <= C_addr_reg_480;
        C_addr_reg_480_pp0_iter9_reg <= C_addr_reg_480_pp0_iter8_reg;
        exitcond_flatten1_reg_403_pp0_iter2_reg <= exitcond_flatten1_reg_403_pp0_iter1_reg;
        exitcond_flatten1_reg_403_pp0_iter3_reg <= exitcond_flatten1_reg_403_pp0_iter2_reg;
        exitcond_flatten1_reg_403_pp0_iter4_reg <= exitcond_flatten1_reg_403_pp0_iter3_reg;
        exitcond_flatten1_reg_403_pp0_iter5_reg <= exitcond_flatten1_reg_403_pp0_iter4_reg;
        exitcond_flatten1_reg_403_pp0_iter6_reg <= exitcond_flatten1_reg_403_pp0_iter5_reg;
        mult_reg_474_pp0_iter7_reg <= mult_reg_474;
        sum_mult_addr_reg_485_pp0_iter10_reg <= sum_mult_addr_reg_485_pp0_iter9_reg;
        sum_mult_addr_reg_485_pp0_iter11_reg <= sum_mult_addr_reg_485_pp0_iter10_reg;
        sum_mult_addr_reg_485_pp0_iter12_reg <= sum_mult_addr_reg_485_pp0_iter11_reg;
        sum_mult_addr_reg_485_pp0_iter13_reg <= sum_mult_addr_reg_485_pp0_iter12_reg;
        sum_mult_addr_reg_485_pp0_iter14_reg <= sum_mult_addr_reg_485_pp0_iter13_reg;
        sum_mult_addr_reg_485_pp0_iter8_reg <= sum_mult_addr_reg_485;
        sum_mult_addr_reg_485_pp0_iter9_reg <= sum_mult_addr_reg_485_pp0_iter8_reg;
        tmp_22_reg_459_pp0_iter2_reg <= tmp_22_reg_459;
        tmp_22_reg_459_pp0_iter3_reg <= tmp_22_reg_459_pp0_iter2_reg;
        tmp_22_reg_459_pp0_iter4_reg <= tmp_22_reg_459_pp0_iter3_reg;
        tmp_22_reg_459_pp0_iter5_reg <= tmp_22_reg_459_pp0_iter4_reg;
        tmp_22_reg_459_pp0_iter6_reg <= tmp_22_reg_459_pp0_iter5_reg;
        tmp_mid2_13_reg_416_pp0_iter10_reg <= tmp_mid2_13_reg_416_pp0_iter9_reg;
        tmp_mid2_13_reg_416_pp0_iter11_reg <= tmp_mid2_13_reg_416_pp0_iter10_reg;
        tmp_mid2_13_reg_416_pp0_iter12_reg <= tmp_mid2_13_reg_416_pp0_iter11_reg;
        tmp_mid2_13_reg_416_pp0_iter13_reg <= tmp_mid2_13_reg_416_pp0_iter12_reg;
        tmp_mid2_13_reg_416_pp0_iter14_reg <= tmp_mid2_13_reg_416_pp0_iter13_reg;
        tmp_mid2_13_reg_416_pp0_iter15_reg <= tmp_mid2_13_reg_416_pp0_iter14_reg;
        tmp_mid2_13_reg_416_pp0_iter2_reg <= tmp_mid2_13_reg_416_pp0_iter1_reg;
        tmp_mid2_13_reg_416_pp0_iter3_reg <= tmp_mid2_13_reg_416_pp0_iter2_reg;
        tmp_mid2_13_reg_416_pp0_iter4_reg <= tmp_mid2_13_reg_416_pp0_iter3_reg;
        tmp_mid2_13_reg_416_pp0_iter5_reg <= tmp_mid2_13_reg_416_pp0_iter4_reg;
        tmp_mid2_13_reg_416_pp0_iter6_reg <= tmp_mid2_13_reg_416_pp0_iter5_reg;
        tmp_mid2_13_reg_416_pp0_iter7_reg <= tmp_mid2_13_reg_416_pp0_iter6_reg;
        tmp_mid2_13_reg_416_pp0_iter8_reg <= tmp_mid2_13_reg_416_pp0_iter7_reg;
        tmp_mid2_13_reg_416_pp0_iter9_reg <= tmp_mid2_13_reg_416_pp0_iter8_reg;
        tmp_mid2_reg_412_pp0_iter10_reg <= tmp_mid2_reg_412_pp0_iter9_reg;
        tmp_mid2_reg_412_pp0_iter11_reg <= tmp_mid2_reg_412_pp0_iter10_reg;
        tmp_mid2_reg_412_pp0_iter12_reg <= tmp_mid2_reg_412_pp0_iter11_reg;
        tmp_mid2_reg_412_pp0_iter13_reg <= tmp_mid2_reg_412_pp0_iter12_reg;
        tmp_mid2_reg_412_pp0_iter14_reg <= tmp_mid2_reg_412_pp0_iter13_reg;
        tmp_mid2_reg_412_pp0_iter15_reg <= tmp_mid2_reg_412_pp0_iter14_reg;
        tmp_mid2_reg_412_pp0_iter2_reg <= tmp_mid2_reg_412_pp0_iter1_reg;
        tmp_mid2_reg_412_pp0_iter3_reg <= tmp_mid2_reg_412_pp0_iter2_reg;
        tmp_mid2_reg_412_pp0_iter4_reg <= tmp_mid2_reg_412_pp0_iter3_reg;
        tmp_mid2_reg_412_pp0_iter5_reg <= tmp_mid2_reg_412_pp0_iter4_reg;
        tmp_mid2_reg_412_pp0_iter6_reg <= tmp_mid2_reg_412_pp0_iter5_reg;
        tmp_mid2_reg_412_pp0_iter7_reg <= tmp_mid2_reg_412_pp0_iter6_reg;
        tmp_mid2_reg_412_pp0_iter8_reg <= tmp_mid2_reg_412_pp0_iter7_reg;
        tmp_mid2_reg_412_pp0_iter9_reg <= tmp_mid2_reg_412_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten1_fu_181_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Col_assign_mid2_reg_427 <= Col_assign_mid2_fu_291_p3;
        tmp_mid2_13_reg_416 <= tmp_mid2_13_fu_245_p3;
        tmp_mid2_reg_412 <= tmp_mid2_fu_225_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_reg_403_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cast_in_a_reg_464 <= A_q0;
        cast_in_b_reg_469 <= B_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond_flatten1_reg_403 <= exitcond_flatten1_fu_181_p2;
        exitcond_flatten1_reg_403_pp0_iter1_reg <= exitcond_flatten1_reg_403;
        tmp_mid2_13_reg_416_pp0_iter1_reg <= tmp_mid2_13_reg_416;
        tmp_mid2_reg_412_pp0_iter1_reg <= tmp_mid2_reg_412;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_reg_403_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mult_reg_474 <= grp_fu_177_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten1_fu_181_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_11_mid2_reg_432 <= tmp_11_mid2_fu_299_p3;
        tmp_i_i_mid2_v_reg_420 <= tmp_i_i_mid2_v_fu_253_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_mid2_reg_412_pp0_iter14_reg == 1'd0))) begin
        tmp_13_reg_496 <= grp_fu_171_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten1_reg_403 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_22_reg_459 <= tmp_22_fu_392_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        A_ce0 = 1'b1;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        B_ce0 = 1'b1;
    end else begin
        B_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter16 == 1'b1))) begin
        C_ce0 = 1'b1;
    end else begin
        C_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter16 == 1'b1) & (tmp_mid2_13_reg_416_pp0_iter15_reg == 1'd1) & (tmp_mid2_reg_412_pp0_iter15_reg == 1'd0))) begin
        C_we0 = 1'b1;
    end else begin
        C_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond_flatten1_fu_181_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_flatten1_reg_403 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_Col_assign_2_phi_fu_131_p4 = tmp_i_i_mid2_v_reg_420;
    end else begin
        ap_phi_mux_Col_assign_2_phi_fu_131_p4 = Col_assign_2_reg_127;
    end
end

always @ (*) begin
    if (((exitcond_flatten1_reg_403 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_Row_assign_phi_fu_153_p4 = tmp_11_mid2_reg_432;
    end else begin
        ap_phi_mux_Row_assign_phi_fu_153_p4 = Row_assign_reg_149;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (tmp_mid2_reg_412_pp0_iter6_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (tmp_mid2_reg_412_pp0_iter6_reg == 1'd0)))) begin
        sum_mult_ce0 = 1'b1;
    end else begin
        sum_mult_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1))) begin
        sum_mult_ce1 = 1'b1;
    end else begin
        sum_mult_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (tmp_mid2_reg_412_pp0_iter6_reg == 1'd1))) begin
        sum_mult_we0 = 1'b1;
    end else begin
        sum_mult_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (tmp_mid2_13_reg_416_pp0_iter14_reg == 1'd0) & (tmp_mid2_reg_412_pp0_iter14_reg == 1'd0))) begin
        sum_mult_we1 = 1'b1;
    end else begin
        sum_mult_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((exitcond_flatten1_fu_181_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter15 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter16 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter15 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter16 == 1'b1)) | ((exitcond_flatten1_fu_181_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = tmp_28_cast_fu_373_p1;

assign B_address0 = tmp_29_cast_fu_387_p1;

assign C_address0 = C_addr_reg_480_pp0_iter15_reg;

assign C_d0 = tmp_13_reg_496;

assign Col_assign_mid2_fu_291_p3 = ((tmp_18_fu_285_p2[0:0] === 1'b1) ? 2'd0 : Col_assign_reg_160);

assign Row_assign_mid_fu_205_p3 = ((exitcond_flatten_fu_199_p2[0:0] === 1'b1) ? 2'd0 : ap_phi_mux_Row_assign_phi_fu_153_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign c_fu_307_p2 = (Col_assign_mid2_fu_291_p3 + 2'd1);

assign exitcond_flatten1_fu_181_p2 = ((indvar_flatten1_reg_116 == 5'd27) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_199_p2 = ((indvar_flatten_reg_138 == 4'd9) ? 1'b1 : 1'b0);

assign exitcond_fu_267_p2 = ((Col_assign_reg_160 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond_mid_fu_273_p2 = (not_exitcond_flatten_fu_261_p2 & exitcond_fu_267_p2);

assign indvar_flatten_next1_fu_187_p2 = (indvar_flatten1_reg_116 + 5'd1);

assign indvar_flatten_next_fu_319_p3 = ((exitcond_flatten_fu_199_p2[0:0] === 1'b1) ? 4'd1 : indvar_flatten_op_fu_313_p2);

assign indvar_flatten_op_fu_313_p2 = (indvar_flatten_reg_138 + 4'd1);

assign k_fu_193_p2 = (ap_phi_mux_Col_assign_2_phi_fu_131_p4 + 2'd1);

assign not_exitcond_flatten_fu_261_p2 = (exitcond_flatten_fu_199_p2 ^ 1'd1);

assign p_shl1_cast_fu_337_p1 = tmp_s_fu_330_p3;

assign p_shl_cast_fu_357_p1 = tmp_fu_350_p3;

assign r_fu_279_p2 = (Row_assign_mid_fu_205_p3 + 2'd1);

assign sum_mult_address0 = tmp_30_cast_fu_398_p1;

assign tmp3_fu_219_p2 = ((ap_phi_mux_Col_assign_2_phi_fu_131_p4 == 2'd0) ? 1'b1 : 1'b0);

assign tmp_11_mid2_cast_fu_347_p1 = tmp_11_mid2_reg_432;

assign tmp_11_mid2_fu_299_p3 = ((exitcond_mid_fu_273_p2[0:0] === 1'b1) ? r_fu_279_p2 : Row_assign_mid_fu_205_p3);

assign tmp_17_fu_341_p2 = (p_shl1_cast_fu_337_p1 - tmp_i_i_mid2_cast_fu_327_p1);

assign tmp_18_fu_285_p2 = (exitcond_mid_fu_273_p2 | exitcond_flatten_fu_199_p2);

assign tmp_19_fu_361_p2 = (p_shl_cast_fu_357_p1 - tmp_11_mid2_cast_fu_347_p1);

assign tmp_20_fu_367_p2 = (tmp_i_i_mid2_cast_fu_327_p1 + tmp_19_fu_361_p2);

assign tmp_21_fu_381_p2 = (tmp_i_i4_cast_fu_378_p1 + tmp_17_fu_341_p2);

assign tmp_22_fu_392_p2 = (tmp_i_i4_cast_fu_378_p1 + tmp_19_fu_361_p2);

assign tmp_28_cast_fu_373_p1 = tmp_20_fu_367_p2;

assign tmp_29_cast_fu_387_p1 = $signed(tmp_21_fu_381_p2);

assign tmp_2_fu_239_p2 = ((ap_phi_mux_Col_assign_2_phi_fu_131_p4 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_30_cast_fu_398_p1 = tmp_22_reg_459_pp0_iter6_reg;

assign tmp_fu_350_p3 = {{tmp_11_mid2_reg_432}, {2'd0}};

assign tmp_i_i4_cast_fu_378_p1 = Col_assign_mid2_reg_427;

assign tmp_i_i_mid2_cast_fu_327_p1 = tmp_i_i_mid2_v_reg_420;

assign tmp_i_i_mid2_v_fu_253_p3 = ((exitcond_flatten_fu_199_p2[0:0] === 1'b1) ? k_fu_193_p2 : ap_phi_mux_Col_assign_2_phi_fu_131_p4);

assign tmp_mid1_12_fu_233_p2 = ((k_fu_193_p2 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_mid1_fu_213_p2 = ((k_fu_193_p2 == 2'd0) ? 1'b1 : 1'b0);

assign tmp_mid2_13_fu_245_p3 = ((exitcond_flatten_fu_199_p2[0:0] === 1'b1) ? tmp_mid1_12_fu_233_p2 : tmp_2_fu_239_p2);

assign tmp_mid2_fu_225_p3 = ((exitcond_flatten_fu_199_p2[0:0] === 1'b1) ? tmp_mid1_fu_213_p2 : tmp3_fu_219_p2);

assign tmp_s_fu_330_p3 = {{tmp_i_i_mid2_v_reg_420}, {2'd0}};

endmodule //matrix_multiply_alt2
