// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _matrix_multiply_top_HH_
#define _matrix_multiply_top_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "matrix_multiply_alt2.h"
#include "matrix_multiply_teOg.h"

namespace ap_rtl {

struct matrix_multiply_top : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<4> > A_address0;
    sc_out< sc_logic > A_ce0;
    sc_in< sc_lv<32> > A_q0;
    sc_out< sc_lv<4> > B_address0;
    sc_out< sc_logic > B_ce0;
    sc_in< sc_lv<32> > B_q0;
    sc_out< sc_lv<4> > C_address0;
    sc_out< sc_logic > C_ce0;
    sc_out< sc_logic > C_we0;
    sc_out< sc_lv<32> > C_d0;


    // Module declarations
    matrix_multiply_top(sc_module_name name);
    SC_HAS_PROCESS(matrix_multiply_top);

    ~matrix_multiply_top();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    matrix_multiply_teOg* a_i_U;
    matrix_multiply_teOg* b_i_U;
    matrix_multiply_teOg* C_assign_U;
    matrix_multiply_alt2* grp_matrix_multiply_alt2_fu_204;
    sc_signal< sc_lv<11> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<2> > r_1_fu_217_p2;
    sc_signal< sc_lv<2> > r_1_reg_394;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<5> > tmp_4_fu_239_p2;
    sc_signal< sc_lv<5> > tmp_4_reg_399;
    sc_signal< sc_lv<1> > tmp_fu_211_p2;
    sc_signal< sc_lv<2> > c_1_fu_251_p2;
    sc_signal< sc_lv<2> > c_1_reg_407;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<64> > tmp_18_cast_fu_266_p1;
    sc_signal< sc_lv<64> > tmp_18_cast_reg_412;
    sc_signal< sc_lv<1> > tmp_3_fu_245_p2;
    sc_signal< sc_lv<2> > r_2_fu_277_p2;
    sc_signal< sc_lv<2> > r_2_reg_425;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<5> > tmp_10_fu_299_p2;
    sc_signal< sc_lv<5> > tmp_10_reg_430;
    sc_signal< sc_lv<1> > tmp_2_fu_271_p2;
    sc_signal< sc_lv<2> > c_2_fu_311_p2;
    sc_signal< sc_lv<2> > c_2_reg_438;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<64> > tmp_21_cast_fu_326_p1;
    sc_signal< sc_lv<64> > tmp_21_cast_reg_443;
    sc_signal< sc_lv<1> > tmp_9_fu_305_p2;
    sc_signal< sc_lv<2> > r_3_fu_337_p2;
    sc_signal< sc_lv<2> > r_3_reg_456;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<5> > tmp_14_fu_359_p2;
    sc_signal< sc_lv<5> > tmp_14_reg_461;
    sc_signal< sc_lv<1> > tmp_8_fu_331_p2;
    sc_signal< sc_lv<2> > c_3_fu_371_p2;
    sc_signal< sc_lv<2> > c_3_reg_469;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<64> > tmp_22_cast_fu_386_p1;
    sc_signal< sc_lv<64> > tmp_22_cast_reg_474;
    sc_signal< sc_lv<1> > tmp_7_fu_365_p2;
    sc_signal< sc_lv<4> > a_i_address0;
    sc_signal< sc_logic > a_i_ce0;
    sc_signal< sc_logic > a_i_we0;
    sc_signal< sc_lv<32> > a_i_q0;
    sc_signal< sc_lv<4> > b_i_address0;
    sc_signal< sc_logic > b_i_ce0;
    sc_signal< sc_logic > b_i_we0;
    sc_signal< sc_lv<32> > b_i_q0;
    sc_signal< sc_lv<4> > C_assign_address0;
    sc_signal< sc_logic > C_assign_ce0;
    sc_signal< sc_logic > C_assign_we0;
    sc_signal< sc_lv<32> > C_assign_q0;
    sc_signal< sc_logic > grp_matrix_multiply_alt2_fu_204_ap_start;
    sc_signal< sc_logic > grp_matrix_multiply_alt2_fu_204_ap_done;
    sc_signal< sc_logic > grp_matrix_multiply_alt2_fu_204_ap_idle;
    sc_signal< sc_logic > grp_matrix_multiply_alt2_fu_204_ap_ready;
    sc_signal< sc_lv<4> > grp_matrix_multiply_alt2_fu_204_A_address0;
    sc_signal< sc_logic > grp_matrix_multiply_alt2_fu_204_A_ce0;
    sc_signal< sc_lv<4> > grp_matrix_multiply_alt2_fu_204_B_address0;
    sc_signal< sc_logic > grp_matrix_multiply_alt2_fu_204_B_ce0;
    sc_signal< sc_lv<4> > grp_matrix_multiply_alt2_fu_204_C_address0;
    sc_signal< sc_logic > grp_matrix_multiply_alt2_fu_204_C_ce0;
    sc_signal< sc_logic > grp_matrix_multiply_alt2_fu_204_C_we0;
    sc_signal< sc_lv<32> > grp_matrix_multiply_alt2_fu_204_C_d0;
    sc_signal< sc_lv<2> > r_reg_138;
    sc_signal< sc_lv<2> > c_reg_149;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<2> > r1_reg_160;
    sc_signal< sc_lv<2> > c2_reg_171;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<2> > r3_reg_182;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<2> > c4_reg_193;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_logic > grp_matrix_multiply_alt2_fu_204_ap_start_reg;
    sc_signal< sc_lv<4> > tmp_1_fu_227_p3;
    sc_signal< sc_lv<5> > p_shl_cast_fu_235_p1;
    sc_signal< sc_lv<5> > tmp_1_cast_fu_223_p1;
    sc_signal< sc_lv<5> > tmp_6_cast_fu_257_p1;
    sc_signal< sc_lv<5> > tmp_11_fu_261_p2;
    sc_signal< sc_lv<4> > tmp_6_fu_287_p3;
    sc_signal< sc_lv<5> > p_shl1_cast_fu_295_p1;
    sc_signal< sc_lv<5> > tmp_4_cast_fu_283_p1;
    sc_signal< sc_lv<5> > tmp_5_cast_fu_317_p1;
    sc_signal< sc_lv<5> > tmp_15_fu_321_p2;
    sc_signal< sc_lv<4> > tmp_13_fu_347_p3;
    sc_signal< sc_lv<5> > p_shl2_cast_fu_355_p1;
    sc_signal< sc_lv<5> > tmp_cast_fu_343_p1;
    sc_signal< sc_lv<5> > tmp_10_cast_fu_377_p1;
    sc_signal< sc_lv<5> > tmp_16_fu_381_p2;
    sc_signal< sc_lv<11> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<11> ap_ST_fsm_state1;
    static const sc_lv<11> ap_ST_fsm_state2;
    static const sc_lv<11> ap_ST_fsm_state3;
    static const sc_lv<11> ap_ST_fsm_state4;
    static const sc_lv<11> ap_ST_fsm_state5;
    static const sc_lv<11> ap_ST_fsm_state6;
    static const sc_lv<11> ap_ST_fsm_state7;
    static const sc_lv<11> ap_ST_fsm_state8;
    static const sc_lv<11> ap_ST_fsm_state9;
    static const sc_lv<11> ap_ST_fsm_state10;
    static const sc_lv<11> ap_ST_fsm_state11;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_A_address0();
    void thread_A_ce0();
    void thread_B_address0();
    void thread_B_ce0();
    void thread_C_address0();
    void thread_C_assign_address0();
    void thread_C_assign_ce0();
    void thread_C_assign_we0();
    void thread_C_ce0();
    void thread_C_d0();
    void thread_C_we0();
    void thread_a_i_address0();
    void thread_a_i_ce0();
    void thread_a_i_we0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_b_i_address0();
    void thread_b_i_ce0();
    void thread_b_i_we0();
    void thread_c_1_fu_251_p2();
    void thread_c_2_fu_311_p2();
    void thread_c_3_fu_371_p2();
    void thread_grp_matrix_multiply_alt2_fu_204_ap_start();
    void thread_p_shl1_cast_fu_295_p1();
    void thread_p_shl2_cast_fu_355_p1();
    void thread_p_shl_cast_fu_235_p1();
    void thread_r_1_fu_217_p2();
    void thread_r_2_fu_277_p2();
    void thread_r_3_fu_337_p2();
    void thread_tmp_10_cast_fu_377_p1();
    void thread_tmp_10_fu_299_p2();
    void thread_tmp_11_fu_261_p2();
    void thread_tmp_13_fu_347_p3();
    void thread_tmp_14_fu_359_p2();
    void thread_tmp_15_fu_321_p2();
    void thread_tmp_16_fu_381_p2();
    void thread_tmp_18_cast_fu_266_p1();
    void thread_tmp_1_cast_fu_223_p1();
    void thread_tmp_1_fu_227_p3();
    void thread_tmp_21_cast_fu_326_p1();
    void thread_tmp_22_cast_fu_386_p1();
    void thread_tmp_2_fu_271_p2();
    void thread_tmp_3_fu_245_p2();
    void thread_tmp_4_cast_fu_283_p1();
    void thread_tmp_4_fu_239_p2();
    void thread_tmp_5_cast_fu_317_p1();
    void thread_tmp_6_cast_fu_257_p1();
    void thread_tmp_6_fu_287_p3();
    void thread_tmp_7_fu_365_p2();
    void thread_tmp_8_fu_331_p2();
    void thread_tmp_9_fu_305_p2();
    void thread_tmp_cast_fu_343_p1();
    void thread_tmp_fu_211_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
