// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "matrix_multiply_alt2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matrix_multiply_alt2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic matrix_multiply_alt2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> matrix_multiply_alt2::ap_ST_fsm_state1 = "1";
const sc_lv<3> matrix_multiply_alt2::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> matrix_multiply_alt2::ap_ST_fsm_state19 = "100";
const bool matrix_multiply_alt2::ap_const_boolean_1 = true;
const sc_lv<32> matrix_multiply_alt2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> matrix_multiply_alt2::ap_const_lv32_1 = "1";
const bool matrix_multiply_alt2::ap_const_boolean_0 = false;
const sc_lv<1> matrix_multiply_alt2::ap_const_lv1_0 = "0";
const sc_lv<1> matrix_multiply_alt2::ap_const_lv1_1 = "1";
const sc_lv<5> matrix_multiply_alt2::ap_const_lv5_0 = "00000";
const sc_lv<2> matrix_multiply_alt2::ap_const_lv2_0 = "00";
const sc_lv<4> matrix_multiply_alt2::ap_const_lv4_0 = "0000";
const sc_lv<5> matrix_multiply_alt2::ap_const_lv5_1B = "11011";
const sc_lv<5> matrix_multiply_alt2::ap_const_lv5_1 = "1";
const sc_lv<2> matrix_multiply_alt2::ap_const_lv2_1 = "1";
const sc_lv<4> matrix_multiply_alt2::ap_const_lv4_9 = "1001";
const sc_lv<2> matrix_multiply_alt2::ap_const_lv2_2 = "10";
const sc_lv<2> matrix_multiply_alt2::ap_const_lv2_3 = "11";
const sc_lv<4> matrix_multiply_alt2::ap_const_lv4_1 = "1";
const sc_lv<32> matrix_multiply_alt2::ap_const_lv32_2 = "10";

matrix_multiply_alt2::matrix_multiply_alt2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sum_mult_U = new matrix_multiply_abkb("sum_mult_U");
    sum_mult_U->clk(ap_clk);
    sum_mult_U->reset(ap_rst);
    sum_mult_U->address0(sum_mult_address0);
    sum_mult_U->ce0(sum_mult_ce0);
    sum_mult_U->we0(sum_mult_we0);
    sum_mult_U->d0(mult_reg_474);
    sum_mult_U->q0(sum_mult_q0);
    sum_mult_U->address1(sum_mult_addr_reg_485_pp0_iter14_reg);
    sum_mult_U->ce1(sum_mult_ce1);
    sum_mult_U->we1(sum_mult_we1);
    sum_mult_U->d1(grp_fu_171_p2);
    matrix_multiply_tcud_U1 = new matrix_multiply_tcud<1,8,32,32,32>("matrix_multiply_tcud_U1");
    matrix_multiply_tcud_U1->clk(ap_clk);
    matrix_multiply_tcud_U1->reset(ap_rst);
    matrix_multiply_tcud_U1->din0(sum_mult_q0);
    matrix_multiply_tcud_U1->din1(mult_reg_474_pp0_iter7_reg);
    matrix_multiply_tcud_U1->ce(ap_var_for_const0);
    matrix_multiply_tcud_U1->dout(grp_fu_171_p2);
    matrix_multiply_tdEe_U2 = new matrix_multiply_tdEe<1,4,32,32,32>("matrix_multiply_tdEe_U2");
    matrix_multiply_tdEe_U2->clk(ap_clk);
    matrix_multiply_tdEe_U2->reset(ap_rst);
    matrix_multiply_tdEe_U2->din0(cast_in_a_reg_464);
    matrix_multiply_tdEe_U2->din1(cast_in_b_reg_469);
    matrix_multiply_tdEe_U2->ce(ap_var_for_const0);
    matrix_multiply_tdEe_U2->dout(grp_fu_177_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_28_cast_fu_373_p1 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_B_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_29_cast_fu_387_p1 );

    SC_METHOD(thread_B_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_C_address0);
    sensitive << ( C_addr_reg_480_pp0_iter15_reg );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_C_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_C_d0);
    sensitive << ( tmp_13_reg_496 );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_C_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_mid2_reg_412_pp0_iter15_reg );
    sensitive << ( tmp_mid2_13_reg_416_pp0_iter15_reg );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_Col_assign_mid2_fu_291_p3);
    sensitive << ( Col_assign_reg_160 );
    sensitive << ( tmp_18_fu_285_p2 );

    SC_METHOD(thread_Row_assign_mid_fu_205_p3);
    sensitive << ( ap_phi_mux_Row_assign_phi_fu_153_p4 );
    sensitive << ( exitcond_flatten_fu_199_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter8);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter10);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter11);

    SC_METHOD(thread_ap_block_state14_pp0_stage0_iter12);

    SC_METHOD(thread_ap_block_state15_pp0_stage0_iter13);

    SC_METHOD(thread_ap_block_state16_pp0_stage0_iter14);

    SC_METHOD(thread_ap_block_state17_pp0_stage0_iter15);

    SC_METHOD(thread_ap_block_state18_pp0_stage0_iter16);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter7);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( exitcond_flatten1_fu_181_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( ap_enable_reg_pp0_iter13 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( ap_enable_reg_pp0_iter15 );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_ap_phi_mux_Col_assign_2_phi_fu_131_p4);
    sensitive << ( Col_assign_2_reg_127 );
    sensitive << ( exitcond_flatten1_reg_403 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_i_i_mid2_v_reg_420 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_Row_assign_phi_fu_153_p4);
    sensitive << ( Row_assign_reg_149 );
    sensitive << ( exitcond_flatten1_reg_403 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_11_mid2_reg_432 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_c_fu_307_p2);
    sensitive << ( Col_assign_mid2_fu_291_p3 );

    SC_METHOD(thread_exitcond_flatten1_fu_181_p2);
    sensitive << ( indvar_flatten1_reg_116 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond_flatten_fu_199_p2);
    sensitive << ( indvar_flatten_reg_138 );
    sensitive << ( exitcond_flatten1_fu_181_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond_fu_267_p2);
    sensitive << ( Col_assign_reg_160 );
    sensitive << ( exitcond_flatten1_fu_181_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond_mid_fu_273_p2);
    sensitive << ( exitcond_fu_267_p2 );
    sensitive << ( not_exitcond_flatten_fu_261_p2 );

    SC_METHOD(thread_indvar_flatten_next1_fu_187_p2);
    sensitive << ( indvar_flatten1_reg_116 );

    SC_METHOD(thread_indvar_flatten_next_fu_319_p3);
    sensitive << ( exitcond_flatten_fu_199_p2 );
    sensitive << ( indvar_flatten_op_fu_313_p2 );

    SC_METHOD(thread_indvar_flatten_op_fu_313_p2);
    sensitive << ( indvar_flatten_reg_138 );

    SC_METHOD(thread_k_fu_193_p2);
    sensitive << ( ap_phi_mux_Col_assign_2_phi_fu_131_p4 );

    SC_METHOD(thread_not_exitcond_flatten_fu_261_p2);
    sensitive << ( exitcond_flatten_fu_199_p2 );

    SC_METHOD(thread_p_shl1_cast_fu_337_p1);
    sensitive << ( tmp_s_fu_330_p3 );

    SC_METHOD(thread_p_shl_cast_fu_357_p1);
    sensitive << ( tmp_fu_350_p3 );

    SC_METHOD(thread_r_fu_279_p2);
    sensitive << ( Row_assign_mid_fu_205_p3 );

    SC_METHOD(thread_sum_mult_address0);
    sensitive << ( tmp_mid2_reg_412_pp0_iter6_reg );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_30_cast_fu_398_p1 );

    SC_METHOD(thread_sum_mult_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_mid2_reg_412_pp0_iter6_reg );
    sensitive << ( ap_enable_reg_pp0_iter7 );

    SC_METHOD(thread_sum_mult_ce1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter15 );

    SC_METHOD(thread_sum_mult_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_mid2_reg_412_pp0_iter6_reg );
    sensitive << ( ap_enable_reg_pp0_iter7 );

    SC_METHOD(thread_sum_mult_we1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_mid2_reg_412_pp0_iter14_reg );
    sensitive << ( tmp_mid2_13_reg_416_pp0_iter14_reg );
    sensitive << ( ap_enable_reg_pp0_iter15 );

    SC_METHOD(thread_tmp3_fu_219_p2);
    sensitive << ( exitcond_flatten1_fu_181_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_Col_assign_2_phi_fu_131_p4 );

    SC_METHOD(thread_tmp_11_mid2_cast_fu_347_p1);
    sensitive << ( tmp_11_mid2_reg_432 );

    SC_METHOD(thread_tmp_11_mid2_fu_299_p3);
    sensitive << ( Row_assign_mid_fu_205_p3 );
    sensitive << ( exitcond_mid_fu_273_p2 );
    sensitive << ( r_fu_279_p2 );

    SC_METHOD(thread_tmp_17_fu_341_p2);
    sensitive << ( p_shl1_cast_fu_337_p1 );
    sensitive << ( tmp_i_i_mid2_cast_fu_327_p1 );

    SC_METHOD(thread_tmp_18_fu_285_p2);
    sensitive << ( exitcond_flatten_fu_199_p2 );
    sensitive << ( exitcond_mid_fu_273_p2 );

    SC_METHOD(thread_tmp_19_fu_361_p2);
    sensitive << ( p_shl_cast_fu_357_p1 );
    sensitive << ( tmp_11_mid2_cast_fu_347_p1 );

    SC_METHOD(thread_tmp_20_fu_367_p2);
    sensitive << ( tmp_i_i_mid2_cast_fu_327_p1 );
    sensitive << ( tmp_19_fu_361_p2 );

    SC_METHOD(thread_tmp_21_fu_381_p2);
    sensitive << ( tmp_i_i4_cast_fu_378_p1 );
    sensitive << ( tmp_17_fu_341_p2 );

    SC_METHOD(thread_tmp_22_fu_392_p2);
    sensitive << ( tmp_19_fu_361_p2 );
    sensitive << ( tmp_i_i4_cast_fu_378_p1 );

    SC_METHOD(thread_tmp_28_cast_fu_373_p1);
    sensitive << ( tmp_20_fu_367_p2 );

    SC_METHOD(thread_tmp_29_cast_fu_387_p1);
    sensitive << ( tmp_21_fu_381_p2 );

    SC_METHOD(thread_tmp_2_fu_239_p2);
    sensitive << ( exitcond_flatten1_fu_181_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_Col_assign_2_phi_fu_131_p4 );

    SC_METHOD(thread_tmp_30_cast_fu_398_p1);
    sensitive << ( tmp_22_reg_459_pp0_iter6_reg );

    SC_METHOD(thread_tmp_fu_350_p3);
    sensitive << ( tmp_11_mid2_reg_432 );

    SC_METHOD(thread_tmp_i_i4_cast_fu_378_p1);
    sensitive << ( Col_assign_mid2_reg_427 );

    SC_METHOD(thread_tmp_i_i_mid2_cast_fu_327_p1);
    sensitive << ( tmp_i_i_mid2_v_reg_420 );

    SC_METHOD(thread_tmp_i_i_mid2_v_fu_253_p3);
    sensitive << ( ap_phi_mux_Col_assign_2_phi_fu_131_p4 );
    sensitive << ( exitcond_flatten_fu_199_p2 );
    sensitive << ( k_fu_193_p2 );

    SC_METHOD(thread_tmp_mid1_12_fu_233_p2);
    sensitive << ( exitcond_flatten1_fu_181_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( k_fu_193_p2 );

    SC_METHOD(thread_tmp_mid1_fu_213_p2);
    sensitive << ( exitcond_flatten1_fu_181_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( k_fu_193_p2 );

    SC_METHOD(thread_tmp_mid2_13_fu_245_p3);
    sensitive << ( exitcond_flatten_fu_199_p2 );
    sensitive << ( tmp_mid1_12_fu_233_p2 );
    sensitive << ( tmp_2_fu_239_p2 );

    SC_METHOD(thread_tmp_mid2_fu_225_p3);
    sensitive << ( exitcond_flatten_fu_199_p2 );
    sensitive << ( tmp_mid1_fu_213_p2 );
    sensitive << ( tmp3_fu_219_p2 );

    SC_METHOD(thread_tmp_s_fu_330_p3);
    sensitive << ( tmp_i_i_mid2_v_reg_420 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( exitcond_flatten1_fu_181_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter15 );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter10 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter11 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter12 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter13 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter14 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter15 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter16 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matrix_multiply_alt2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, B_address0, "(port)B_address0");
    sc_trace(mVcdFile, B_ce0, "(port)B_ce0");
    sc_trace(mVcdFile, B_q0, "(port)B_q0");
    sc_trace(mVcdFile, C_address0, "(port)C_address0");
    sc_trace(mVcdFile, C_ce0, "(port)C_ce0");
    sc_trace(mVcdFile, C_we0, "(port)C_we0");
    sc_trace(mVcdFile, C_d0, "(port)C_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten1_reg_116, "indvar_flatten1_reg_116");
    sc_trace(mVcdFile, Col_assign_2_reg_127, "Col_assign_2_reg_127");
    sc_trace(mVcdFile, indvar_flatten_reg_138, "indvar_flatten_reg_138");
    sc_trace(mVcdFile, Row_assign_reg_149, "Row_assign_reg_149");
    sc_trace(mVcdFile, Col_assign_reg_160, "Col_assign_reg_160");
    sc_trace(mVcdFile, exitcond_flatten1_fu_181_p2, "exitcond_flatten1_fu_181_p2");
    sc_trace(mVcdFile, exitcond_flatten1_reg_403, "exitcond_flatten1_reg_403");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter4, "ap_block_state6_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter5, "ap_block_state7_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter6, "ap_block_state8_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter7, "ap_block_state9_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter8, "ap_block_state10_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter9, "ap_block_state11_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter10, "ap_block_state12_pp0_stage0_iter10");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter11, "ap_block_state13_pp0_stage0_iter11");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage0_iter12, "ap_block_state14_pp0_stage0_iter12");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage0_iter13, "ap_block_state15_pp0_stage0_iter13");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage0_iter14, "ap_block_state16_pp0_stage0_iter14");
    sc_trace(mVcdFile, ap_block_state17_pp0_stage0_iter15, "ap_block_state17_pp0_stage0_iter15");
    sc_trace(mVcdFile, ap_block_state18_pp0_stage0_iter16, "ap_block_state18_pp0_stage0_iter16");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exitcond_flatten1_reg_403_pp0_iter1_reg, "exitcond_flatten1_reg_403_pp0_iter1_reg");
    sc_trace(mVcdFile, exitcond_flatten1_reg_403_pp0_iter2_reg, "exitcond_flatten1_reg_403_pp0_iter2_reg");
    sc_trace(mVcdFile, exitcond_flatten1_reg_403_pp0_iter3_reg, "exitcond_flatten1_reg_403_pp0_iter3_reg");
    sc_trace(mVcdFile, exitcond_flatten1_reg_403_pp0_iter4_reg, "exitcond_flatten1_reg_403_pp0_iter4_reg");
    sc_trace(mVcdFile, exitcond_flatten1_reg_403_pp0_iter5_reg, "exitcond_flatten1_reg_403_pp0_iter5_reg");
    sc_trace(mVcdFile, exitcond_flatten1_reg_403_pp0_iter6_reg, "exitcond_flatten1_reg_403_pp0_iter6_reg");
    sc_trace(mVcdFile, indvar_flatten_next1_fu_187_p2, "indvar_flatten_next1_fu_187_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_mid2_fu_225_p3, "tmp_mid2_fu_225_p3");
    sc_trace(mVcdFile, tmp_mid2_reg_412, "tmp_mid2_reg_412");
    sc_trace(mVcdFile, tmp_mid2_reg_412_pp0_iter1_reg, "tmp_mid2_reg_412_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_mid2_reg_412_pp0_iter2_reg, "tmp_mid2_reg_412_pp0_iter2_reg");
    sc_trace(mVcdFile, tmp_mid2_reg_412_pp0_iter3_reg, "tmp_mid2_reg_412_pp0_iter3_reg");
    sc_trace(mVcdFile, tmp_mid2_reg_412_pp0_iter4_reg, "tmp_mid2_reg_412_pp0_iter4_reg");
    sc_trace(mVcdFile, tmp_mid2_reg_412_pp0_iter5_reg, "tmp_mid2_reg_412_pp0_iter5_reg");
    sc_trace(mVcdFile, tmp_mid2_reg_412_pp0_iter6_reg, "tmp_mid2_reg_412_pp0_iter6_reg");
    sc_trace(mVcdFile, tmp_mid2_reg_412_pp0_iter7_reg, "tmp_mid2_reg_412_pp0_iter7_reg");
    sc_trace(mVcdFile, tmp_mid2_reg_412_pp0_iter8_reg, "tmp_mid2_reg_412_pp0_iter8_reg");
    sc_trace(mVcdFile, tmp_mid2_reg_412_pp0_iter9_reg, "tmp_mid2_reg_412_pp0_iter9_reg");
    sc_trace(mVcdFile, tmp_mid2_reg_412_pp0_iter10_reg, "tmp_mid2_reg_412_pp0_iter10_reg");
    sc_trace(mVcdFile, tmp_mid2_reg_412_pp0_iter11_reg, "tmp_mid2_reg_412_pp0_iter11_reg");
    sc_trace(mVcdFile, tmp_mid2_reg_412_pp0_iter12_reg, "tmp_mid2_reg_412_pp0_iter12_reg");
    sc_trace(mVcdFile, tmp_mid2_reg_412_pp0_iter13_reg, "tmp_mid2_reg_412_pp0_iter13_reg");
    sc_trace(mVcdFile, tmp_mid2_reg_412_pp0_iter14_reg, "tmp_mid2_reg_412_pp0_iter14_reg");
    sc_trace(mVcdFile, tmp_mid2_reg_412_pp0_iter15_reg, "tmp_mid2_reg_412_pp0_iter15_reg");
    sc_trace(mVcdFile, tmp_mid2_13_fu_245_p3, "tmp_mid2_13_fu_245_p3");
    sc_trace(mVcdFile, tmp_mid2_13_reg_416, "tmp_mid2_13_reg_416");
    sc_trace(mVcdFile, tmp_mid2_13_reg_416_pp0_iter1_reg, "tmp_mid2_13_reg_416_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_mid2_13_reg_416_pp0_iter2_reg, "tmp_mid2_13_reg_416_pp0_iter2_reg");
    sc_trace(mVcdFile, tmp_mid2_13_reg_416_pp0_iter3_reg, "tmp_mid2_13_reg_416_pp0_iter3_reg");
    sc_trace(mVcdFile, tmp_mid2_13_reg_416_pp0_iter4_reg, "tmp_mid2_13_reg_416_pp0_iter4_reg");
    sc_trace(mVcdFile, tmp_mid2_13_reg_416_pp0_iter5_reg, "tmp_mid2_13_reg_416_pp0_iter5_reg");
    sc_trace(mVcdFile, tmp_mid2_13_reg_416_pp0_iter6_reg, "tmp_mid2_13_reg_416_pp0_iter6_reg");
    sc_trace(mVcdFile, tmp_mid2_13_reg_416_pp0_iter7_reg, "tmp_mid2_13_reg_416_pp0_iter7_reg");
    sc_trace(mVcdFile, tmp_mid2_13_reg_416_pp0_iter8_reg, "tmp_mid2_13_reg_416_pp0_iter8_reg");
    sc_trace(mVcdFile, tmp_mid2_13_reg_416_pp0_iter9_reg, "tmp_mid2_13_reg_416_pp0_iter9_reg");
    sc_trace(mVcdFile, tmp_mid2_13_reg_416_pp0_iter10_reg, "tmp_mid2_13_reg_416_pp0_iter10_reg");
    sc_trace(mVcdFile, tmp_mid2_13_reg_416_pp0_iter11_reg, "tmp_mid2_13_reg_416_pp0_iter11_reg");
    sc_trace(mVcdFile, tmp_mid2_13_reg_416_pp0_iter12_reg, "tmp_mid2_13_reg_416_pp0_iter12_reg");
    sc_trace(mVcdFile, tmp_mid2_13_reg_416_pp0_iter13_reg, "tmp_mid2_13_reg_416_pp0_iter13_reg");
    sc_trace(mVcdFile, tmp_mid2_13_reg_416_pp0_iter14_reg, "tmp_mid2_13_reg_416_pp0_iter14_reg");
    sc_trace(mVcdFile, tmp_mid2_13_reg_416_pp0_iter15_reg, "tmp_mid2_13_reg_416_pp0_iter15_reg");
    sc_trace(mVcdFile, tmp_i_i_mid2_v_fu_253_p3, "tmp_i_i_mid2_v_fu_253_p3");
    sc_trace(mVcdFile, tmp_i_i_mid2_v_reg_420, "tmp_i_i_mid2_v_reg_420");
    sc_trace(mVcdFile, Col_assign_mid2_fu_291_p3, "Col_assign_mid2_fu_291_p3");
    sc_trace(mVcdFile, Col_assign_mid2_reg_427, "Col_assign_mid2_reg_427");
    sc_trace(mVcdFile, tmp_11_mid2_fu_299_p3, "tmp_11_mid2_fu_299_p3");
    sc_trace(mVcdFile, tmp_11_mid2_reg_432, "tmp_11_mid2_reg_432");
    sc_trace(mVcdFile, c_fu_307_p2, "c_fu_307_p2");
    sc_trace(mVcdFile, indvar_flatten_next_fu_319_p3, "indvar_flatten_next_fu_319_p3");
    sc_trace(mVcdFile, tmp_22_fu_392_p2, "tmp_22_fu_392_p2");
    sc_trace(mVcdFile, tmp_22_reg_459, "tmp_22_reg_459");
    sc_trace(mVcdFile, tmp_22_reg_459_pp0_iter2_reg, "tmp_22_reg_459_pp0_iter2_reg");
    sc_trace(mVcdFile, tmp_22_reg_459_pp0_iter3_reg, "tmp_22_reg_459_pp0_iter3_reg");
    sc_trace(mVcdFile, tmp_22_reg_459_pp0_iter4_reg, "tmp_22_reg_459_pp0_iter4_reg");
    sc_trace(mVcdFile, tmp_22_reg_459_pp0_iter5_reg, "tmp_22_reg_459_pp0_iter5_reg");
    sc_trace(mVcdFile, tmp_22_reg_459_pp0_iter6_reg, "tmp_22_reg_459_pp0_iter6_reg");
    sc_trace(mVcdFile, cast_in_a_reg_464, "cast_in_a_reg_464");
    sc_trace(mVcdFile, cast_in_b_reg_469, "cast_in_b_reg_469");
    sc_trace(mVcdFile, grp_fu_177_p2, "grp_fu_177_p2");
    sc_trace(mVcdFile, mult_reg_474, "mult_reg_474");
    sc_trace(mVcdFile, mult_reg_474_pp0_iter7_reg, "mult_reg_474_pp0_iter7_reg");
    sc_trace(mVcdFile, C_addr_reg_480, "C_addr_reg_480");
    sc_trace(mVcdFile, C_addr_reg_480_pp0_iter8_reg, "C_addr_reg_480_pp0_iter8_reg");
    sc_trace(mVcdFile, C_addr_reg_480_pp0_iter9_reg, "C_addr_reg_480_pp0_iter9_reg");
    sc_trace(mVcdFile, C_addr_reg_480_pp0_iter10_reg, "C_addr_reg_480_pp0_iter10_reg");
    sc_trace(mVcdFile, C_addr_reg_480_pp0_iter11_reg, "C_addr_reg_480_pp0_iter11_reg");
    sc_trace(mVcdFile, C_addr_reg_480_pp0_iter12_reg, "C_addr_reg_480_pp0_iter12_reg");
    sc_trace(mVcdFile, C_addr_reg_480_pp0_iter13_reg, "C_addr_reg_480_pp0_iter13_reg");
    sc_trace(mVcdFile, C_addr_reg_480_pp0_iter14_reg, "C_addr_reg_480_pp0_iter14_reg");
    sc_trace(mVcdFile, C_addr_reg_480_pp0_iter15_reg, "C_addr_reg_480_pp0_iter15_reg");
    sc_trace(mVcdFile, sum_mult_addr_reg_485, "sum_mult_addr_reg_485");
    sc_trace(mVcdFile, sum_mult_addr_reg_485_pp0_iter8_reg, "sum_mult_addr_reg_485_pp0_iter8_reg");
    sc_trace(mVcdFile, sum_mult_addr_reg_485_pp0_iter9_reg, "sum_mult_addr_reg_485_pp0_iter9_reg");
    sc_trace(mVcdFile, sum_mult_addr_reg_485_pp0_iter10_reg, "sum_mult_addr_reg_485_pp0_iter10_reg");
    sc_trace(mVcdFile, sum_mult_addr_reg_485_pp0_iter11_reg, "sum_mult_addr_reg_485_pp0_iter11_reg");
    sc_trace(mVcdFile, sum_mult_addr_reg_485_pp0_iter12_reg, "sum_mult_addr_reg_485_pp0_iter12_reg");
    sc_trace(mVcdFile, sum_mult_addr_reg_485_pp0_iter13_reg, "sum_mult_addr_reg_485_pp0_iter13_reg");
    sc_trace(mVcdFile, sum_mult_addr_reg_485_pp0_iter14_reg, "sum_mult_addr_reg_485_pp0_iter14_reg");
    sc_trace(mVcdFile, sum_mult_q0, "sum_mult_q0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, grp_fu_171_p2, "grp_fu_171_p2");
    sc_trace(mVcdFile, tmp_13_reg_496, "tmp_13_reg_496");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter10, "ap_enable_reg_pp0_iter10");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter11, "ap_enable_reg_pp0_iter11");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter12, "ap_enable_reg_pp0_iter12");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter13, "ap_enable_reg_pp0_iter13");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter14, "ap_enable_reg_pp0_iter14");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter15, "ap_enable_reg_pp0_iter15");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter16, "ap_enable_reg_pp0_iter16");
    sc_trace(mVcdFile, sum_mult_address0, "sum_mult_address0");
    sc_trace(mVcdFile, sum_mult_ce0, "sum_mult_ce0");
    sc_trace(mVcdFile, sum_mult_we0, "sum_mult_we0");
    sc_trace(mVcdFile, sum_mult_ce1, "sum_mult_ce1");
    sc_trace(mVcdFile, sum_mult_we1, "sum_mult_we1");
    sc_trace(mVcdFile, ap_phi_mux_Col_assign_2_phi_fu_131_p4, "ap_phi_mux_Col_assign_2_phi_fu_131_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_Row_assign_phi_fu_153_p4, "ap_phi_mux_Row_assign_phi_fu_153_p4");
    sc_trace(mVcdFile, tmp_28_cast_fu_373_p1, "tmp_28_cast_fu_373_p1");
    sc_trace(mVcdFile, tmp_29_cast_fu_387_p1, "tmp_29_cast_fu_387_p1");
    sc_trace(mVcdFile, tmp_30_cast_fu_398_p1, "tmp_30_cast_fu_398_p1");
    sc_trace(mVcdFile, exitcond_flatten_fu_199_p2, "exitcond_flatten_fu_199_p2");
    sc_trace(mVcdFile, k_fu_193_p2, "k_fu_193_p2");
    sc_trace(mVcdFile, tmp_mid1_fu_213_p2, "tmp_mid1_fu_213_p2");
    sc_trace(mVcdFile, tmp3_fu_219_p2, "tmp3_fu_219_p2");
    sc_trace(mVcdFile, tmp_mid1_12_fu_233_p2, "tmp_mid1_12_fu_233_p2");
    sc_trace(mVcdFile, tmp_2_fu_239_p2, "tmp_2_fu_239_p2");
    sc_trace(mVcdFile, exitcond_fu_267_p2, "exitcond_fu_267_p2");
    sc_trace(mVcdFile, not_exitcond_flatten_fu_261_p2, "not_exitcond_flatten_fu_261_p2");
    sc_trace(mVcdFile, Row_assign_mid_fu_205_p3, "Row_assign_mid_fu_205_p3");
    sc_trace(mVcdFile, exitcond_mid_fu_273_p2, "exitcond_mid_fu_273_p2");
    sc_trace(mVcdFile, tmp_18_fu_285_p2, "tmp_18_fu_285_p2");
    sc_trace(mVcdFile, r_fu_279_p2, "r_fu_279_p2");
    sc_trace(mVcdFile, indvar_flatten_op_fu_313_p2, "indvar_flatten_op_fu_313_p2");
    sc_trace(mVcdFile, tmp_s_fu_330_p3, "tmp_s_fu_330_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_337_p1, "p_shl1_cast_fu_337_p1");
    sc_trace(mVcdFile, tmp_i_i_mid2_cast_fu_327_p1, "tmp_i_i_mid2_cast_fu_327_p1");
    sc_trace(mVcdFile, tmp_fu_350_p3, "tmp_fu_350_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_357_p1, "p_shl_cast_fu_357_p1");
    sc_trace(mVcdFile, tmp_11_mid2_cast_fu_347_p1, "tmp_11_mid2_cast_fu_347_p1");
    sc_trace(mVcdFile, tmp_19_fu_361_p2, "tmp_19_fu_361_p2");
    sc_trace(mVcdFile, tmp_20_fu_367_p2, "tmp_20_fu_367_p2");
    sc_trace(mVcdFile, tmp_i_i4_cast_fu_378_p1, "tmp_i_i4_cast_fu_378_p1");
    sc_trace(mVcdFile, tmp_17_fu_341_p2, "tmp_17_fu_341_p2");
    sc_trace(mVcdFile, tmp_21_fu_381_p2, "tmp_21_fu_381_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

matrix_multiply_alt2::~matrix_multiply_alt2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sum_mult_U;
    delete matrix_multiply_tcud_U1;
    delete matrix_multiply_tdEe_U2;
}

void matrix_multiply_alt2::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void matrix_multiply_alt2::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten1_reg_403.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        Col_assign_2_reg_127 = tmp_i_i_mid2_v_reg_420.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        Col_assign_2_reg_127 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_fu_181_p2.read(), ap_const_lv1_0))) {
        Col_assign_reg_160 = c_fu_307_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        Col_assign_reg_160 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten1_reg_403.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        Row_assign_reg_149 = tmp_11_mid2_reg_432.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        Row_assign_reg_149 = ap_const_lv2_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter10 = ap_enable_reg_pp0_iter9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter11 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter11 = ap_enable_reg_pp0_iter10.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter12 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter12 = ap_enable_reg_pp0_iter11.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter13 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter13 = ap_enable_reg_pp0_iter12.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter14 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter14 = ap_enable_reg_pp0_iter13.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter15 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter15 = ap_enable_reg_pp0_iter14.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter16 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter16 = ap_enable_reg_pp0_iter15.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter16 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_fu_181_p2.read(), ap_const_lv1_0))) {
        indvar_flatten1_reg_116 = indvar_flatten_next1_fu_187_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten1_reg_116 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_fu_181_p2.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_138 = indvar_flatten_next_fu_319_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten_reg_138 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten1_reg_403_pp0_iter6_reg.read(), ap_const_lv1_0))) {
        C_addr_reg_480 =  (sc_lv<4>) (tmp_30_cast_fu_398_p1.read());
        sum_mult_addr_reg_485 =  (sc_lv<4>) (tmp_30_cast_fu_398_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        C_addr_reg_480_pp0_iter10_reg = C_addr_reg_480_pp0_iter9_reg.read();
        C_addr_reg_480_pp0_iter11_reg = C_addr_reg_480_pp0_iter10_reg.read();
        C_addr_reg_480_pp0_iter12_reg = C_addr_reg_480_pp0_iter11_reg.read();
        C_addr_reg_480_pp0_iter13_reg = C_addr_reg_480_pp0_iter12_reg.read();
        C_addr_reg_480_pp0_iter14_reg = C_addr_reg_480_pp0_iter13_reg.read();
        C_addr_reg_480_pp0_iter15_reg = C_addr_reg_480_pp0_iter14_reg.read();
        C_addr_reg_480_pp0_iter8_reg = C_addr_reg_480.read();
        C_addr_reg_480_pp0_iter9_reg = C_addr_reg_480_pp0_iter8_reg.read();
        exitcond_flatten1_reg_403_pp0_iter2_reg = exitcond_flatten1_reg_403_pp0_iter1_reg.read();
        exitcond_flatten1_reg_403_pp0_iter3_reg = exitcond_flatten1_reg_403_pp0_iter2_reg.read();
        exitcond_flatten1_reg_403_pp0_iter4_reg = exitcond_flatten1_reg_403_pp0_iter3_reg.read();
        exitcond_flatten1_reg_403_pp0_iter5_reg = exitcond_flatten1_reg_403_pp0_iter4_reg.read();
        exitcond_flatten1_reg_403_pp0_iter6_reg = exitcond_flatten1_reg_403_pp0_iter5_reg.read();
        mult_reg_474_pp0_iter7_reg = mult_reg_474.read();
        sum_mult_addr_reg_485_pp0_iter10_reg = sum_mult_addr_reg_485_pp0_iter9_reg.read();
        sum_mult_addr_reg_485_pp0_iter11_reg = sum_mult_addr_reg_485_pp0_iter10_reg.read();
        sum_mult_addr_reg_485_pp0_iter12_reg = sum_mult_addr_reg_485_pp0_iter11_reg.read();
        sum_mult_addr_reg_485_pp0_iter13_reg = sum_mult_addr_reg_485_pp0_iter12_reg.read();
        sum_mult_addr_reg_485_pp0_iter14_reg = sum_mult_addr_reg_485_pp0_iter13_reg.read();
        sum_mult_addr_reg_485_pp0_iter8_reg = sum_mult_addr_reg_485.read();
        sum_mult_addr_reg_485_pp0_iter9_reg = sum_mult_addr_reg_485_pp0_iter8_reg.read();
        tmp_22_reg_459_pp0_iter2_reg = tmp_22_reg_459.read();
        tmp_22_reg_459_pp0_iter3_reg = tmp_22_reg_459_pp0_iter2_reg.read();
        tmp_22_reg_459_pp0_iter4_reg = tmp_22_reg_459_pp0_iter3_reg.read();
        tmp_22_reg_459_pp0_iter5_reg = tmp_22_reg_459_pp0_iter4_reg.read();
        tmp_22_reg_459_pp0_iter6_reg = tmp_22_reg_459_pp0_iter5_reg.read();
        tmp_mid2_13_reg_416_pp0_iter10_reg = tmp_mid2_13_reg_416_pp0_iter9_reg.read();
        tmp_mid2_13_reg_416_pp0_iter11_reg = tmp_mid2_13_reg_416_pp0_iter10_reg.read();
        tmp_mid2_13_reg_416_pp0_iter12_reg = tmp_mid2_13_reg_416_pp0_iter11_reg.read();
        tmp_mid2_13_reg_416_pp0_iter13_reg = tmp_mid2_13_reg_416_pp0_iter12_reg.read();
        tmp_mid2_13_reg_416_pp0_iter14_reg = tmp_mid2_13_reg_416_pp0_iter13_reg.read();
        tmp_mid2_13_reg_416_pp0_iter15_reg = tmp_mid2_13_reg_416_pp0_iter14_reg.read();
        tmp_mid2_13_reg_416_pp0_iter2_reg = tmp_mid2_13_reg_416_pp0_iter1_reg.read();
        tmp_mid2_13_reg_416_pp0_iter3_reg = tmp_mid2_13_reg_416_pp0_iter2_reg.read();
        tmp_mid2_13_reg_416_pp0_iter4_reg = tmp_mid2_13_reg_416_pp0_iter3_reg.read();
        tmp_mid2_13_reg_416_pp0_iter5_reg = tmp_mid2_13_reg_416_pp0_iter4_reg.read();
        tmp_mid2_13_reg_416_pp0_iter6_reg = tmp_mid2_13_reg_416_pp0_iter5_reg.read();
        tmp_mid2_13_reg_416_pp0_iter7_reg = tmp_mid2_13_reg_416_pp0_iter6_reg.read();
        tmp_mid2_13_reg_416_pp0_iter8_reg = tmp_mid2_13_reg_416_pp0_iter7_reg.read();
        tmp_mid2_13_reg_416_pp0_iter9_reg = tmp_mid2_13_reg_416_pp0_iter8_reg.read();
        tmp_mid2_reg_412_pp0_iter10_reg = tmp_mid2_reg_412_pp0_iter9_reg.read();
        tmp_mid2_reg_412_pp0_iter11_reg = tmp_mid2_reg_412_pp0_iter10_reg.read();
        tmp_mid2_reg_412_pp0_iter12_reg = tmp_mid2_reg_412_pp0_iter11_reg.read();
        tmp_mid2_reg_412_pp0_iter13_reg = tmp_mid2_reg_412_pp0_iter12_reg.read();
        tmp_mid2_reg_412_pp0_iter14_reg = tmp_mid2_reg_412_pp0_iter13_reg.read();
        tmp_mid2_reg_412_pp0_iter15_reg = tmp_mid2_reg_412_pp0_iter14_reg.read();
        tmp_mid2_reg_412_pp0_iter2_reg = tmp_mid2_reg_412_pp0_iter1_reg.read();
        tmp_mid2_reg_412_pp0_iter3_reg = tmp_mid2_reg_412_pp0_iter2_reg.read();
        tmp_mid2_reg_412_pp0_iter4_reg = tmp_mid2_reg_412_pp0_iter3_reg.read();
        tmp_mid2_reg_412_pp0_iter5_reg = tmp_mid2_reg_412_pp0_iter4_reg.read();
        tmp_mid2_reg_412_pp0_iter6_reg = tmp_mid2_reg_412_pp0_iter5_reg.read();
        tmp_mid2_reg_412_pp0_iter7_reg = tmp_mid2_reg_412_pp0_iter6_reg.read();
        tmp_mid2_reg_412_pp0_iter8_reg = tmp_mid2_reg_412_pp0_iter7_reg.read();
        tmp_mid2_reg_412_pp0_iter9_reg = tmp_mid2_reg_412_pp0_iter8_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten1_fu_181_p2.read(), ap_const_lv1_0))) {
        Col_assign_mid2_reg_427 = Col_assign_mid2_fu_291_p3.read();
        tmp_mid2_13_reg_416 = tmp_mid2_13_fu_245_p3.read();
        tmp_mid2_reg_412 = tmp_mid2_fu_225_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten1_reg_403_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        cast_in_a_reg_464 = A_q0.read();
        cast_in_b_reg_469 = B_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_flatten1_reg_403 = exitcond_flatten1_fu_181_p2.read();
        exitcond_flatten1_reg_403_pp0_iter1_reg = exitcond_flatten1_reg_403.read();
        tmp_mid2_13_reg_416_pp0_iter1_reg = tmp_mid2_13_reg_416.read();
        tmp_mid2_reg_412_pp0_iter1_reg = tmp_mid2_reg_412.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten1_reg_403_pp0_iter5_reg.read(), ap_const_lv1_0))) {
        mult_reg_474 = grp_fu_177_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(exitcond_flatten1_fu_181_p2.read(), ap_const_lv1_0))) {
        tmp_11_mid2_reg_432 = tmp_11_mid2_fu_299_p3.read();
        tmp_i_i_mid2_v_reg_420 = tmp_i_i_mid2_v_fu_253_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_mid2_reg_412_pp0_iter14_reg.read()))) {
        tmp_13_reg_496 = grp_fu_171_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten1_reg_403.read(), ap_const_lv1_0))) {
        tmp_22_reg_459 = tmp_22_fu_392_p2.read();
    }
}

void matrix_multiply_alt2::thread_A_address0() {
    A_address0 =  (sc_lv<4>) (tmp_28_cast_fu_373_p1.read());
}

void matrix_multiply_alt2::thread_A_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        A_ce0 = ap_const_logic_1;
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void matrix_multiply_alt2::thread_B_address0() {
    B_address0 =  (sc_lv<4>) (tmp_29_cast_fu_387_p1.read());
}

void matrix_multiply_alt2::thread_B_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        B_ce0 = ap_const_logic_1;
    } else {
        B_ce0 = ap_const_logic_0;
    }
}

void matrix_multiply_alt2::thread_C_address0() {
    C_address0 = C_addr_reg_480_pp0_iter15_reg.read();
}

void matrix_multiply_alt2::thread_C_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()))) {
        C_ce0 = ap_const_logic_1;
    } else {
        C_ce0 = ap_const_logic_0;
    }
}

void matrix_multiply_alt2::thread_C_d0() {
    C_d0 = tmp_13_reg_496.read();
}

void matrix_multiply_alt2::thread_C_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_mid2_reg_412_pp0_iter15_reg.read()) && 
         esl_seteq<1,1,1>(tmp_mid2_13_reg_416_pp0_iter15_reg.read(), ap_const_lv1_1))) {
        C_we0 = ap_const_logic_1;
    } else {
        C_we0 = ap_const_logic_0;
    }
}

void matrix_multiply_alt2::thread_Col_assign_mid2_fu_291_p3() {
    Col_assign_mid2_fu_291_p3 = (!tmp_18_fu_285_p2.read()[0].is_01())? sc_lv<2>(): ((tmp_18_fu_285_p2.read()[0].to_bool())? ap_const_lv2_0: Col_assign_reg_160.read());
}

void matrix_multiply_alt2::thread_Row_assign_mid_fu_205_p3() {
    Row_assign_mid_fu_205_p3 = (!exitcond_flatten_fu_199_p2.read()[0].is_01())? sc_lv<2>(): ((exitcond_flatten_fu_199_p2.read()[0].to_bool())? ap_const_lv2_0: ap_phi_mux_Row_assign_phi_fu_153_p4.read());
}

void matrix_multiply_alt2::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void matrix_multiply_alt2::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void matrix_multiply_alt2::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[2];
}

void matrix_multiply_alt2::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state10_pp0_stage0_iter8() {
    ap_block_state10_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state11_pp0_stage0_iter9() {
    ap_block_state11_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state12_pp0_stage0_iter10() {
    ap_block_state12_pp0_stage0_iter10 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state13_pp0_stage0_iter11() {
    ap_block_state13_pp0_stage0_iter11 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state14_pp0_stage0_iter12() {
    ap_block_state14_pp0_stage0_iter12 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state15_pp0_stage0_iter13() {
    ap_block_state15_pp0_stage0_iter13 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state16_pp0_stage0_iter14() {
    ap_block_state16_pp0_stage0_iter14 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state17_pp0_stage0_iter15() {
    ap_block_state17_pp0_stage0_iter15 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state18_pp0_stage0_iter16() {
    ap_block_state18_pp0_stage0_iter16 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state6_pp0_stage0_iter4() {
    ap_block_state6_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state7_pp0_stage0_iter5() {
    ap_block_state7_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state8_pp0_stage0_iter6() {
    ap_block_state8_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_block_state9_pp0_stage0_iter7() {
    ap_block_state9_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_alt2::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(exitcond_flatten1_fu_181_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void matrix_multiply_alt2::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void matrix_multiply_alt2::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void matrix_multiply_alt2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void matrix_multiply_alt2::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter12.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter13.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter14.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter15.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter16.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void matrix_multiply_alt2::thread_ap_phi_mux_Col_assign_2_phi_fu_131_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_reg_403.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_Col_assign_2_phi_fu_131_p4 = tmp_i_i_mid2_v_reg_420.read();
    } else {
        ap_phi_mux_Col_assign_2_phi_fu_131_p4 = Col_assign_2_reg_127.read();
    }
}

void matrix_multiply_alt2::thread_ap_phi_mux_Row_assign_phi_fu_153_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_reg_403.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_Row_assign_phi_fu_153_p4 = tmp_11_mid2_reg_432.read();
    } else {
        ap_phi_mux_Row_assign_phi_fu_153_p4 = Row_assign_reg_149.read();
    }
}

void matrix_multiply_alt2::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void matrix_multiply_alt2::thread_c_fu_307_p2() {
    c_fu_307_p2 = (!Col_assign_mid2_fu_291_p3.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Col_assign_mid2_fu_291_p3.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_multiply_alt2::thread_exitcond_flatten1_fu_181_p2() {
    exitcond_flatten1_fu_181_p2 = (!indvar_flatten1_reg_116.read().is_01() || !ap_const_lv5_1B.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten1_reg_116.read() == ap_const_lv5_1B);
}

void matrix_multiply_alt2::thread_exitcond_flatten_fu_199_p2() {
    exitcond_flatten_fu_199_p2 = (!indvar_flatten_reg_138.read().is_01() || !ap_const_lv4_9.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_138.read() == ap_const_lv4_9);
}

void matrix_multiply_alt2::thread_exitcond_fu_267_p2() {
    exitcond_fu_267_p2 = (!Col_assign_reg_160.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(Col_assign_reg_160.read() == ap_const_lv2_3);
}

void matrix_multiply_alt2::thread_exitcond_mid_fu_273_p2() {
    exitcond_mid_fu_273_p2 = (exitcond_fu_267_p2.read() & not_exitcond_flatten_fu_261_p2.read());
}

void matrix_multiply_alt2::thread_indvar_flatten_next1_fu_187_p2() {
    indvar_flatten_next1_fu_187_p2 = (!indvar_flatten1_reg_116.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(indvar_flatten1_reg_116.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void matrix_multiply_alt2::thread_indvar_flatten_next_fu_319_p3() {
    indvar_flatten_next_fu_319_p3 = (!exitcond_flatten_fu_199_p2.read()[0].is_01())? sc_lv<4>(): ((exitcond_flatten_fu_199_p2.read()[0].to_bool())? ap_const_lv4_1: indvar_flatten_op_fu_313_p2.read());
}

void matrix_multiply_alt2::thread_indvar_flatten_op_fu_313_p2() {
    indvar_flatten_op_fu_313_p2 = (!indvar_flatten_reg_138.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(indvar_flatten_reg_138.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void matrix_multiply_alt2::thread_k_fu_193_p2() {
    k_fu_193_p2 = (!ap_phi_mux_Col_assign_2_phi_fu_131_p4.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(ap_phi_mux_Col_assign_2_phi_fu_131_p4.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_multiply_alt2::thread_not_exitcond_flatten_fu_261_p2() {
    not_exitcond_flatten_fu_261_p2 = (exitcond_flatten_fu_199_p2.read() ^ ap_const_lv1_1);
}

void matrix_multiply_alt2::thread_p_shl1_cast_fu_337_p1() {
    p_shl1_cast_fu_337_p1 = esl_zext<5,4>(tmp_s_fu_330_p3.read());
}

void matrix_multiply_alt2::thread_p_shl_cast_fu_357_p1() {
    p_shl_cast_fu_357_p1 = esl_zext<5,4>(tmp_fu_350_p3.read());
}

void matrix_multiply_alt2::thread_r_fu_279_p2() {
    r_fu_279_p2 = (!Row_assign_mid_fu_205_p3.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Row_assign_mid_fu_205_p3.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_multiply_alt2::thread_sum_mult_address0() {
    sum_mult_address0 =  (sc_lv<4>) (tmp_30_cast_fu_398_p1.read());
}

void matrix_multiply_alt2::thread_sum_mult_ce0() {
    if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_mid2_reg_412_pp0_iter6_reg.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
          esl_seteq<1,1,1>(tmp_mid2_reg_412_pp0_iter6_reg.read(), ap_const_lv1_1)))) {
        sum_mult_ce0 = ap_const_logic_1;
    } else {
        sum_mult_ce0 = ap_const_logic_0;
    }
}

void matrix_multiply_alt2::thread_sum_mult_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter15.read()))) {
        sum_mult_ce1 = ap_const_logic_1;
    } else {
        sum_mult_ce1 = ap_const_logic_0;
    }
}

void matrix_multiply_alt2::thread_sum_mult_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(tmp_mid2_reg_412_pp0_iter6_reg.read(), ap_const_lv1_1))) {
        sum_mult_we0 = ap_const_logic_1;
    } else {
        sum_mult_we0 = ap_const_logic_0;
    }
}

void matrix_multiply_alt2::thread_sum_mult_we1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_mid2_reg_412_pp0_iter14_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter15.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_mid2_13_reg_416_pp0_iter14_reg.read()))) {
        sum_mult_we1 = ap_const_logic_1;
    } else {
        sum_mult_we1 = ap_const_logic_0;
    }
}

void matrix_multiply_alt2::thread_tmp3_fu_219_p2() {
    tmp3_fu_219_p2 = (!ap_phi_mux_Col_assign_2_phi_fu_131_p4.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_Col_assign_2_phi_fu_131_p4.read() == ap_const_lv2_0);
}

void matrix_multiply_alt2::thread_tmp_11_mid2_cast_fu_347_p1() {
    tmp_11_mid2_cast_fu_347_p1 = esl_zext<5,2>(tmp_11_mid2_reg_432.read());
}

void matrix_multiply_alt2::thread_tmp_11_mid2_fu_299_p3() {
    tmp_11_mid2_fu_299_p3 = (!exitcond_mid_fu_273_p2.read()[0].is_01())? sc_lv<2>(): ((exitcond_mid_fu_273_p2.read()[0].to_bool())? r_fu_279_p2.read(): Row_assign_mid_fu_205_p3.read());
}

void matrix_multiply_alt2::thread_tmp_17_fu_341_p2() {
    tmp_17_fu_341_p2 = (!p_shl1_cast_fu_337_p1.read().is_01() || !tmp_i_i_mid2_cast_fu_327_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl1_cast_fu_337_p1.read()) - sc_biguint<5>(tmp_i_i_mid2_cast_fu_327_p1.read()));
}

void matrix_multiply_alt2::thread_tmp_18_fu_285_p2() {
    tmp_18_fu_285_p2 = (exitcond_mid_fu_273_p2.read() | exitcond_flatten_fu_199_p2.read());
}

void matrix_multiply_alt2::thread_tmp_19_fu_361_p2() {
    tmp_19_fu_361_p2 = (!p_shl_cast_fu_357_p1.read().is_01() || !tmp_11_mid2_cast_fu_347_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl_cast_fu_357_p1.read()) - sc_biguint<5>(tmp_11_mid2_cast_fu_347_p1.read()));
}

void matrix_multiply_alt2::thread_tmp_20_fu_367_p2() {
    tmp_20_fu_367_p2 = (!tmp_i_i_mid2_cast_fu_327_p1.read().is_01() || !tmp_19_fu_361_p2.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_i_i_mid2_cast_fu_327_p1.read()) + sc_biguint<5>(tmp_19_fu_361_p2.read()));
}

void matrix_multiply_alt2::thread_tmp_21_fu_381_p2() {
    tmp_21_fu_381_p2 = (!tmp_i_i4_cast_fu_378_p1.read().is_01() || !tmp_17_fu_341_p2.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_i_i4_cast_fu_378_p1.read()) + sc_biguint<5>(tmp_17_fu_341_p2.read()));
}

void matrix_multiply_alt2::thread_tmp_22_fu_392_p2() {
    tmp_22_fu_392_p2 = (!tmp_i_i4_cast_fu_378_p1.read().is_01() || !tmp_19_fu_361_p2.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_i_i4_cast_fu_378_p1.read()) + sc_biguint<5>(tmp_19_fu_361_p2.read()));
}

void matrix_multiply_alt2::thread_tmp_28_cast_fu_373_p1() {
    tmp_28_cast_fu_373_p1 = esl_zext<64,5>(tmp_20_fu_367_p2.read());
}

void matrix_multiply_alt2::thread_tmp_29_cast_fu_387_p1() {
    tmp_29_cast_fu_387_p1 = esl_sext<64,5>(tmp_21_fu_381_p2.read());
}

void matrix_multiply_alt2::thread_tmp_2_fu_239_p2() {
    tmp_2_fu_239_p2 = (!ap_phi_mux_Col_assign_2_phi_fu_131_p4.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_Col_assign_2_phi_fu_131_p4.read() == ap_const_lv2_2);
}

void matrix_multiply_alt2::thread_tmp_30_cast_fu_398_p1() {
    tmp_30_cast_fu_398_p1 = esl_zext<64,5>(tmp_22_reg_459_pp0_iter6_reg.read());
}

void matrix_multiply_alt2::thread_tmp_fu_350_p3() {
    tmp_fu_350_p3 = esl_concat<2,2>(tmp_11_mid2_reg_432.read(), ap_const_lv2_0);
}

void matrix_multiply_alt2::thread_tmp_i_i4_cast_fu_378_p1() {
    tmp_i_i4_cast_fu_378_p1 = esl_zext<5,2>(Col_assign_mid2_reg_427.read());
}

void matrix_multiply_alt2::thread_tmp_i_i_mid2_cast_fu_327_p1() {
    tmp_i_i_mid2_cast_fu_327_p1 = esl_zext<5,2>(tmp_i_i_mid2_v_reg_420.read());
}

void matrix_multiply_alt2::thread_tmp_i_i_mid2_v_fu_253_p3() {
    tmp_i_i_mid2_v_fu_253_p3 = (!exitcond_flatten_fu_199_p2.read()[0].is_01())? sc_lv<2>(): ((exitcond_flatten_fu_199_p2.read()[0].to_bool())? k_fu_193_p2.read(): ap_phi_mux_Col_assign_2_phi_fu_131_p4.read());
}

void matrix_multiply_alt2::thread_tmp_mid1_12_fu_233_p2() {
    tmp_mid1_12_fu_233_p2 = (!k_fu_193_p2.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(k_fu_193_p2.read() == ap_const_lv2_2);
}

void matrix_multiply_alt2::thread_tmp_mid1_fu_213_p2() {
    tmp_mid1_fu_213_p2 = (!k_fu_193_p2.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(k_fu_193_p2.read() == ap_const_lv2_0);
}

void matrix_multiply_alt2::thread_tmp_mid2_13_fu_245_p3() {
    tmp_mid2_13_fu_245_p3 = (!exitcond_flatten_fu_199_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_199_p2.read()[0].to_bool())? tmp_mid1_12_fu_233_p2.read(): tmp_2_fu_239_p2.read());
}

void matrix_multiply_alt2::thread_tmp_mid2_fu_225_p3() {
    tmp_mid2_fu_225_p3 = (!exitcond_flatten_fu_199_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_199_p2.read()[0].to_bool())? tmp_mid1_fu_213_p2.read(): tmp3_fu_219_p2.read());
}

void matrix_multiply_alt2::thread_tmp_s_fu_330_p3() {
    tmp_s_fu_330_p3 = esl_concat<2,2>(tmp_i_i_mid2_v_reg_420.read(), ap_const_lv2_0);
}

void matrix_multiply_alt2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter15.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten1_fu_181_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter15.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(exitcond_flatten1_fu_181_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state19;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

